title: Refactoring Family Java Project
description: Refactoring, Code Quality and Software Architecture Project

url: "https://csdt-eci.github.io"
baseurl: "/Refactoring-family-java-bad-code"

# Sin remote_theme para que el diseño custom no sea interferido
plugins: []

# Footer
footer_content: "Proyecto académico - CSDT"

# Links externos
aux_links:
  "GitHub Repository":
    - "https://github.com/CSDT-ECI/Refactoring-family-java-bad-code"