title: Refactoring Family Java Project
description: Refactoring, Code Quality and Software Architecture Project

url: "https://csdt-eci.github.io"
baseurl: "/Refactoring-family-java-bad-code"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

nav_enabled: true
nav_sort: case_insensitive
search_enabled: true

color_scheme: dark
heading_anchors: true
back_to_top: true

footer_content: "Proyecto académico · CSDT"

aux_links:
  "GitHub →":
    - "https://github.com/CSDT-ECI/Refactoring-family-java-bad-code"